import ChatHistorySection from "@/components/chat-history";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Engage Realtime | Chat",
  description: "Generated by create next app",
};
const ChatPageLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div className="h-svh container px-1 mx-auto pb-2 pt-20 flex items-center gap-2">
      {/* Chat History */}
      <div className="hidden lg:flex h-full lg:w-80 p-1">
        <ChatHistorySection />
      </div>
      {/* Message Section */}
      <div className="h-full w-full">{children}</div>
    </div>
  );
};

export default ChatPageLayout;
